repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.12.10
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.8
    hooks:
      - id: pylint
        entry: .venv/bin/pylint
  - repo: https://github.com/facelessuser/pyspelling
    rev: '2.12.1'
    hooks:
      - id: pyspelling
        verbose: true
        args: ['-n', 'ortografia']
  - repo: https://github.com/rstcheck/rstcheck
    rev: 'v6.3.0'
    hooks:
      - id: rstcheck
        entry: .venv/bin/rstcheck
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.5.12
    hooks:
      - id: biome-check
        name: biome-check
        files: '\.(js|css)$'
  - repo: local
    hooks:
      - id: diccionario
        name: diccionario
        entry: scripts/corregir_diccionario.py
        language: python
        files: es-local.dic
