[project]
name = "cpeum"
version = "0.1.0"
description = "Constitución Política de los Estados Unidos Mexicanos"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4",
    "lxml",
    "docutils",
    "rstcheck",
    "pylint",
    "pyspelling",
    "pre-commit",
    "ruff",
    "chevron>=0.14.0",
]
