name: BlueSky

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  bluesky:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    environment:
      name: BlueSky

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check if PR contains document changes
        id: check
        run: |
          SUBJECT=$(git log -1 --format=%s HEAD)
          FILES=$(git show --name-only --format='' HEAD | grep "^CPEUM/.*\.rst$" || true)

          if echo "$SUBJECT" | grep -qi -e "artículo" -e "articulo" && [ -n "$FILES" ]; then
            echo "document_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "document_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract commit description
        if: steps.check.outputs.document_changes == 'true'
        id: desc
        run: |
          git log -1 --format=%B HEAD | awk -v RS='' 'NR == 2' | sed ':a;N;$!ba;s/\n/ /g' | awk '{print "desc=" $0}' >> "$GITHUB_OUTPUT"

      - name: Post in BlueSky
        if: steps.check.outputs.document_changes == 'true'
        uses: zentered/bluesky-post-action@v0.2.0
        with:
          post: |
            ${{ steps.desc.outputs.desc }}

            ${{ github.event.pull_request._links.html.href }}
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
