name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install aspell aspell-es

      - name: Maximum line length
        run: awk '{ if (length($0) > 72) { print FILENAME " " FNR; exit 255 } }' CPEUM/[T0-9]*.rst

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python
        run: uv python install '3.12'

      - name: Install Python dependencies
        run: uv sync --frozen

      - name: Check spelling
        run: uv run pyspelling -n ortografia

      - name: Check reStructuredText syntax
        run: uv run rstcheck -r CPEUM/

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python
        run: uv python install '3.12'

      - name: Install Python dependencies
        run: uv sync --frozen

      - name: Generate document
        run: |
          mkdir html
          cd CPEUM
          uv run ../scripts/rst2html5.py toc.rst ../html/index.html

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: html

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
